SELECT 
	"FIPS" || '-' || "YEAR" AS uid,
	CASE WHEN "YEAR" = 2009 THEN 2008 ELSE "YEAR" END as year,
	"COUNTY" as county,
	"GEO_STATE_FIPS" as GEO_STATE_FIPS,
	"GEO_COUNTY_FIPS" as GEO_COUNTY_FIPS,
    RIGHT("FIPS", 5) as FIPS_SHORT,
	"FIPS" as FIPS,
	"POPULATION_TOTAL" as POPULATION_TOTAL,
	"INCOME_MEDIAN_INCOME_12_MONTH" as INCOME_MEDIAN_INCOME_12_MONTH,
	"POPULATION_DENSITY" as POPULATION_DENSITY,
	"RATIO_MALE" as RATIO_MALE,
	"RATIO_FEMALE" as RATIO_FEMALE,
	"RATIO_WHITE" as RATIO_WHITE,
	"RATIO_HISPANIC" as RATIO_HISPANIC,
	"RATIO_POPULATION_BLACK_ALL" as RATIO_POPULATION_BLACK_ALL,
	"RATIO_POPULATION_DEGREE" as RATIO_POPULATION_DEGREE
FROM {{ source('demo_data', 'census_data') }}